export default {
  input: "src/index.js",
  output: {
    file: "dist/vacuum-orchestrator-card.js",
    format: "iife",
    strict: true,
    indent: false,
    sourcemap: process.env.VACUUM_ORCHESTRATOR_CARD_COVERAGE === "1" ? "inline" : false,
    banner:
      "/* Vacuum Orchestrator Card — generated by `npm run build` from src/. Do not edit.\n" +
      "   Source, tests and documentation: https://github.com/hyperfelixations/vacuum-orchestrator-card */",
  },
  treeshake: false,
  onwarn(warning) {
    throw new Error(`Rollup warning treated as an error (${warning.code}): ${warning.message}`);
  },
};
