import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { rollup } from "rollup";
import productConfig from "../rollup.config.mjs";

const MODULE_PATH = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(MODULE_PATH), "..");
const METADATA_PATH = path.join(ROOT, "src", "core", "card-metadata.js");
const REPOSITORY_URL = "https://github.com/hyperfelixations/vacuum-orchestrator-card";
export const DEV_OUTPUT = path.join(ROOT, "dist", "vacuum-orchestrator-card-dev.js");

export function versionGlobalFor(cardType) {
  return `${cardType.replace(/-([a-z0-9])/g, (_, letter) => letter.toUpperCase())}Version`;
}

export function buildStamp(date) {
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
}

export function deriveDevIdentity(metadata, { builtAt, commit = null, dirty = false }) {
  const expected = versionGlobalFor(metadata.CARD_TYPE);
  if (expected !== metadata.CARD_VERSION_GLOBAL) throw new Error(`card-metadata.js: CARD_VERSION_GLOBAL "${metadata.CARD_VERSION_GLOBAL}" does not follow from CARD_TYPE "${metadata.CARD_TYPE}" (expected "${expected}")`);
  const cardType = `${metadata.CARD_TYPE}-dev`;
  const build = [buildStamp(builtAt), commit, commit && dirty ? "dirty" : null].filter(Boolean).join(".");
  return { CARD_TYPE: cardType, CARD_NAME: `${metadata.CARD_NAME} (Dev)`, CARD_VERSION: `${metadata.CARD_VERSION}-dev+${build}`, CARD_VERSION_GLOBAL: versionGlobalFor(cardType) };
}

export function assertSameExports(metadataExports, identity) {
  const actual = [...metadataExports].sort();
  const derived = Object.keys(identity).sort();
  if (actual.join() !== derived.join()) throw new Error(`card-metadata.js exports ${actual.join(", ")}, but the dev build derives ${derived.join(", ")} — extend deriveDevIdentity() in scripts/build-dev.mjs`);
}

export function devMetadataSource(identity) {
  return `// Development identity from scripts/build-dev.mjs\n${Object.entries(identity).map(([key, value]) => `export const ${key} = ${JSON.stringify(value)};`).join("\n")}\n`;
}

export function readGitInfo(cwd = ROOT) {
  const run = (args) => spawnSync("git", args, { cwd, encoding: "utf8" });
  const head = run(["rev-parse", "--short", "HEAD"]);
  if (head.error || head.status !== 0) return { commit: null, dirty: false };
  const status = run(["status", "--porcelain"]);
  return { commit: head.stdout.trim(), dirty: status.status !== 0 || Boolean(status.stdout.trim()) };
}

function banner(identity, { builtAt, commit, dirty }) {
  const origin = commit ? `commit ${commit}${dirty ? " with uncommitted changes" : ""}` : "a checkout without Git";
  return [`/* ${identity.CARD_NAME} ${identity.CARD_VERSION} — DEVELOPMENT BUILD, not a release.`, `   Generated by \`npm run build:dev\` from ${origin} at ${builtAt.toISOString()}. Do not edit.`, `   Registers <${identity.CARD_TYPE}> beside the released card: use \`type: custom:${identity.CARD_TYPE}\`.`, `   Source, tests and documentation: ${REPOSITORY_URL} */`].join("\n");
}

export async function buildDevBundle({ outFile = DEV_OUTPUT, builtAt = new Date(), git = readGitInfo() } = {}) {
  const metadata = await import(pathToFileURL(METADATA_PATH).href);
  const identity = deriveDevIdentity(metadata, { builtAt, ...git });
  assertSameExports(Object.keys(metadata), identity);
  let replaced = false;
  const bundle = await rollup({
    input: path.join(ROOT, productConfig.input),
    treeshake: productConfig.treeshake,
    onwarn: productConfig.onwarn,
    plugins: [{ name: "vacuum-orchestrator-card-dev-identity", load(id) {
      if (path.resolve(id) !== path.resolve(METADATA_PATH)) return null;
      replaced = true;
      return devMetadataSource(identity);
    } }],
  });
  try {
    if (!replaced) throw new Error("src/core/card-metadata.js is not part of the bundle graph");
    await bundle.write({ ...productConfig.output, file: outFile, sourcemap: false, banner: banner(identity, { builtAt, ...git }), outro: `console.info(${JSON.stringify(`${identity.CARD_NAME} ${identity.CARD_VERSION}`)});` });
  } finally {
    await bundle.close();
  }
  return { outFile, identity, stamp: buildStamp(builtAt) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === MODULE_PATH) {
  buildDevBundle().then(({ outFile, identity, stamp }) => {
    const check = spawnSync(process.execPath, ["--check", outFile], { stdio: "inherit" });
    if (check.status !== 0) throw new Error(`node --check rejected ${outFile}`);
    const bytes = fs.readFileSync(outFile);
    console.log(`Development build written to ${path.relative(ROOT, outFile).replaceAll(path.sep, "/")} (${bytes.length} bytes, SHA-256 ${crypto.createHash("sha256").update(bytes).digest("hex")})\n  card type       custom:${identity.CARD_TYPE}\n  version         ${identity.CARD_VERSION}\n  resource URL    /local/${path.basename(outFile)}?v=${stamp}`);
  }).catch((error) => { console.error(`Development build failed: ${error.message}`); process.exitCode = 1; });
}
